### ISSUE TITLE
shift in w space rather than z space

### ISSUE THREAD

**Issue by zhuzhu18** [chi0tzp/WarpedGANSpace#4]
https://github.com/chi0tzp/WarpedGANSpace/blob/5b89eb894b03cf20edd8df1fb4952486f7367c6d/traverse_latent_space.py#L423

I think this line should be commented out, you set shift in w space, so it need not to add shift in z noise vector. The shift will be added to the w space of the generator after that.

**Comment by chi0tzp** [comment]
@zhuzhu18 thanks for bringing this to my attention. I had the opportunity to improve the code/documentation a bit.
