### ISSUE TITLE
support  biggan、stylegan 1 、2  and  stylegan-ada  ？

### ISSUE THREAD

**Issue by zhanghongyong123456** [chi0tzp/WarpedGANSpace#5]

**Comment by chi0tzp** [comment]
Hi @zhanghongyong123456, for the time being the repo supports [BigGAN](https://github.com/ajbrock/BigGAN-PyTorch) and [StyleGAN2](https://github.com/anvoynov/GANLatentDiscovery). However, I plan to migrate to GenForce's implementations (BigGAB, StyleGAN1, and StyleGAN2 at least) soon.
