### ISSUE TITLE
Generalizing to other GANs

### ISSUE THREAD

**Issue by mmitchef** [chi0tzp/WarpedGANSpace#7]
Thanks for sharing your code and paper. It’s really interesting and this is the topic that I was looking for.
I was wondering whether this code can be used for any styleGAN (e.g stylegan3) which is trained on a custom dataset?

**Comment by chi0tzp** [comment]
Hi @mmitchef thanks for your interest. The method can generalise to any GAN and for any latent space. I'm planning to update the repo for more StyleGANs but I do not have any concrete schedule at the moment.

**Comment by mmitchef** [comment]
@chi0tzp excellent and thanks for your response.

**Comment by mmitchef** [comment]
> Hi @mmitchef thanks for your interest. The method can generalise to any GAN and for any latent space. I'm planning to update the repo for more StyleGANs but I do not have any concrete schedule at the moment.

Excellent and thanks for responding.
