### ISSUE TITLE
How to plot the path related to image traversal

### ISSUE THREAD

**Issue by mmitchef** [chi0tzp/WarpedGANSpace#9]
Hello,
Could you please give me some hints how I can get the path for each support set (warping function)? I got the images for each support set and I want to plot the actual path as well (by path I mean dashed black lines in Figure (1) both (a) and (b))?
Thanks

**Comment by chi0tzp** [comment]
Hi @mmitchef, the traversals you see in Fig. 1 are only for illustrating the idea -- there, the latent space is supposed to be 2-dimensional, and that the resulting curves (driven by the gradient of the warping function) can be depicted on the plane. In the case of a real latent space (e.g., the 512-dimensional space of a ProgGAN or StyleGAN2), this is not possible. 

However, you can measure what we define as phi in the paper (for getting a quantitative measure of the non-linearity).
